### ISSUE TITLE
Couleurs

### ISSUE THREAD

**Issue by adrien-f** [adrien-f/battleship#1]
Voici un exemple des couleurs que nous pourrions utiliser:

![battleship_colors](https://cloud.githubusercontent.com/assets/781688/16156128/fe0803a4-34b2-11e6-8b84-abe0d21efaf4.png)

Vous en pensez quoi ?

**Comment by tristanfabre** [comment]
ME GUSTA 10/10

**Comment by Psycokeb** [comment]
AWESOME THX BRO !!!
